const SKILL_CHARA = {"はらぺこ大将":["Special Week"],
"夢叶える末脚":["Special Week"],
"真夏の思い切り":["Special Week（Summer）"],
"真夏の総大将":["Special Week（Summer）"],
"怒涛の出陣":["Special Week（Commander）"],
"日之本一のド根性":["Special Week（Commander）"],
"最大集中":["Silence Suzuka"],
"異次元の逃亡者":["Silence Suzuka"],
"天才的技巧":["Tokai Teio"],
"帝王ステップ":["Tokai Teio"],
"レースの天才":["Tokai Teio（Anime Collab）"],
"地平の彼方まで":["Tokai Teio（Anime Collab）"],
"かっ飛ばすわよ！":["Maruzensky"],
"紅蓮のオーバーレブ":["Maruzensky"],
"ドキッ☆じゃじゃウマ娘！":["Maruzensky（Summer）"],
"お立ち台の支配者":["Maruzensky（Summer）"],
"輝くトップスタァ":["Fuji Kiseki"],
"エンターテイナー":["Fuji Kiseki"],
"圧巻のトリック":["Fuji Kiseki（Ballroom）"],
"煌めきのトップスタァ":["Fuji Kiseki（Ballroom）"],
"笠松の食いしん坊":["Oguri Cap"],
"怪物的コーナリング":["Oguri Cap"],
"ドカ食い養生":["Oguri Cap（Christmas）"],
"クリスマスの奇跡体験":["Oguri Cap（Christmas）"],
"564アイズで視界クッキリ！":["Gold Ship"],
"エクストリーム下校術":["Gold Ship"],
"神秘体験！ゴルシワープ":["Gold Ship（Summer）"],
"イカ揚げ、いかがですか！？":["Gold Ship（Summer）"],
"スキットルブレイク":["Vodka"],
"抜群の豪脚":["Vodka"],
"ぶっ差してやるぜ！":["Vodka（Christmas）"],
"最速のトップギア":["Vodka（Christmas）"],
"パーフェクトチューン":["Daiwa Scarlet"],
"アタシが勝つんだから！":["Daiwa Scarlet"],
"おてんば女王":["Daiwa Scarlet（Christmas）"],
"開かれる夢の扉":["Daiwa Scarlet（Christmas）"],
"狙い撃ちデス！":["Taiki Shuttle"],
"Frontier Spirit":["Taiki Shuttle"],
"アドベンチャーの先導者":["Taiki Shuttle（Camping）"],
"真剣勝負デス！":["Taiki Shuttle（Camping）"],
"大和撫子":["Grass Wonder"],
"不退転の意思":["Grass Wonder"],
"キュアリーヒール":["Grass Wonder（Fantasy）"],
"勇気の魔法":["Grass Wonder（Fantasy）"],
"勝利への咆哮":["Hishi Amazon"],
"怒濤のポロロッカ":["Hishi Amazon"],
"メジロの心得":["Mejiro McQueen"],
"名優の余裕":["Mejiro McQueen"],
"アクティブレスト":["Mejiro McQueen（Anime Collab）"],
"空の果てまで":["Mejiro McQueen（Anime Collab）"],
"夏の名優":["Mejiro McQueen（Summer）"],
"一意専心にリフレッシュ！":["Mejiro McQueen（Summer）"],
"鷹ノ目":["El Condor Pasa"],
"余裕のパフォーマンス":["El Condor Pasa"],
"豪勇無双":["El Condor Pasa（Fantasy）"],
"昇りコンドル":["El Condor Pasa（Fantasy）"],
"降臨！世紀末覇王！":["TM Opera O"],
"歌劇王の行進":["TM Opera O"],
"円舞曲のマエストロ":["TM Opera O（New Year）"],
"ボクは遅れずにやってくる！":["TM Opera O（New Year）"],
"一刀両断":["Narita Brian"],
"餓狼牙":["Narita Brian"],
"BLAZING WOLF":["Narita Brian（Blaze）"],
"渇望する怪物":["Narita Brian（Blaze）"],
"皇帝の眼差し":["Symboli Rudolf"],
"鎧袖一触":["Symboli Rudolf"],
"神色自若":["Symboli Rudolf（Festival）"],
"風霜高潔":["Symboli Rudolf（Festival）"],
"女帝の権謀":["Air Groove"],
"水月鏡花":["Air Groove"],
"女帝の矜持":["Air Groove（Wedding）"],
"上弦のソムリエール":["Air Groove（Wedding）"],
"限界ウママニア":["Agnes Digital"],
"最前列は譲れない！":["Agnes Digital"],
"超特急入稿！":["Agnes Digital（Halloween）"],
"尊みを求めてふっかーーつ！":["Agnes Digital（Halloween）"],
"ファストリトリーブ":["Seiun Sky"],
"脱出大作戦":["Seiun Sky"],
"逃げろ～♪":["Seiun Sky（Ballroom）"],
"レコードランナー":["Seiun Sky（Ballroom）"],
"雷騰雲奔":["Tamamo Cross"],
"尻尾の有頂天":["Tamamo Cross"],
"先達に献ぐ祈りの頌":["Tamamo Cross（Festival）"],
"さあ、ウチとやろうや！":["Tamamo Cross（Festival）"],
"ロイヤルスター":["Fine Motion"],
"天空落とし":["Fine Motion"],
"思い出を力に変えて":["Fine Motion（Wedding）"],
"モリガンの矛戟":["Fine Motion（Wedding）"],
"想定通り、余裕十分":["Biwa Hayahide"],
"計画的クールダウン":["Biwa Hayahide"],
"VIPな後ろ姿":["Biwa Hayahide（Christmas）"],
"全力サンタクロース":["Biwa Hayahide（Christmas）"],
"You copy?":["Mayano Top Gun"],
"I copy!":["Mayano Top Gun"],
"純白のささやき":["Mayano Top Gun（Wedding）"],
"バレルロール":["Mayano Top Gun（Wedding）"],
"コーヒーブレイク":["Manhattan Cafe"],
"オイテイカナイデ":["Manhattan Cafe"],
"クロックアップ":["Mihono Bourbon"],
"困難を乗り越える者":["Mihono Bourbon"],
"完璧なエラー対処術":["Mihono Bourbon（Valentine）"],
"パーフェクトブート":["Mihono Bourbon（Valentine）"],
"マッスルアンセム":["Mejiro Ryan"],
"ライジングバルクアップ":["Mejiro Ryan"],
"夢叶える決意を授けましょう":["Mejiro Ryan（Valentine）"],
"至高の勝利を召し上がれ":["Mejiro Ryan（Valentine）"],
"下ごしらえ万全！":["Hishi Akebono"],
"ボーノな健啖家":["Hishi Akebono"],
"憧れのシチーガール":["Yukino Bijin"],
"雪国仕込みの直滑降":["Yukino Bijin"],
"決意のヒーロー":["Rice Shower"],
"黒の刺客":["Rice Shower"],
"がんばるぞー…おー！":["Rice Shower（Halloween）"],
"トリック&トリート":["Rice Shower（Halloween）"],
"じゃじゃウマお姉ちゃん":["Ines Fujin"],
"荒ぶる風神":["Ines Fujin"],
"オーダーはバッチリ！":["Ines Fujin（Valentine）"],
"華麗なサーブ":["Ines Fujin（Valentine）"],
"可能性の徒":["Agnes Tachyon"],
"効率的休息法":["Agnes Tachyon"],
"静かな誓い":["Admire Vega"],
"己身焦がすほうき星":["Admire Vega"],
"火消の梯子登り":["Inari One"],
"熟練の砂塵使い":["Inari One"],
"扇ノ舞":["Inari One（Festival）"],
"大見得切り":["Inari One（Festival）"],
"たゆまぬ努力":["Winning Ticket"],
"ウイニングロード":["Winning Ticket"],
"千万バリキ！！！":["Winning Ticket（Steampunk）"],
"きっと飛べる！":["Winning Ticket（Steampunk）"],
"アップリフティング":["Air Shakur"],
"Lose Myself":["Air Shakur"],
"閃光のマギア":["Eishin Flash"],
"誇りを懸けて":["Eishin Flash"],
"勝利のレシピ":["Eishin Flash（Valentine）"],
"黒い閃光":["Eishin Flash（Valentine）"],
"#カワイイかく乱♪":["Curren Chan"],
"#夢中になっちゃえ♪":["Curren Chan"],
"#カレンに染まってみる？":["Curren Chan（Wedding）"],
"#ビューティースプリント":["Curren Chan（Wedding）"],
"ノンストッププリンセス":["Kawakami Princess"],
"暴れ龍":["Kawakami Princess"],
"先見の明":["Gold City"],
"ランウェイの主役":["Gold City"],
"鮮やかな布陣":["Gold City（Festival）"],
"虎視眈々":["Gold City（Festival）"],
"バクシン的スプリント！":["Sakura Bakushin O"],
"バクシン的リード！":["Sakura Bakushin O"],
"世界を貫く至高の輝き":["Seeking the Pearl"],
"パール流ダンスバトル":["Seeking the Pearl"],
"全速前進なのだ！":["Shinko Windy"],
"いたずらマイスター":["Shinko Windy"],
"放課後魔法少女":["Sweep Tosho"],
"チャームマジック":["Sweep Tosho"],
"あま～い幻惑":["Super Creek"],
"癒しのマエストロ":["Super Creek"],
"お世話のプロフェッショナル":["Super Creek（Halloween）"],
"魅惑のマミーウィスパー":["Super Creek（Halloween）"],
"大注目のウマドル参上★":["Smart Falcon"],
"ウマドルパワー急上昇↑↑":["Smart Falcon"],
"夢に向かって急上昇！":["Smart Falcon（Grand Live）"],
"絶対的センター！":["Smart Falcon（Grand Live）"],
"英雄への道標":["Zenno Rob Roy"],
"光輝く剣":["Zenno Rob Roy"],
"ノってこ！":["Tosen Jordan"],
"トレンドプランナー":["Tosen Jordan"],
"乾坤一擲の大博打":["Nakayama Festa"],
"鉄火のギャンブラー":["Nakayama Festa"],
"鬼気森然":["Narita Taishin"],
"駆り立てる想い":["Narita Taishin"],
"見せつけてやる！":["Narita Taishin（Steampunk）"],
"起死回生の出力":["Narita Taishin（Steampunk）"],
"風花疾走":["Nishino Flower"],
"大輪の決意":["Nishino Flower"],
"まだまだだよ！":["Haru Urara"],
"まけないからね！":["Haru Urara"],
"見てて見てて！":["Haru Urara（New Year）"],
"がんばるもん！":["Haru Urara（New Year）"],
"風紀の登龍門":["Bamboo Memory"],
"押忍ッ！気合十分っス！":["Bamboo Memory"],
"吉兆です！":["Matikane- fukukitaru"],
"七福即生":["Matikane- fukukitaru"],
"怒涛の超幸運パワー！":["Matikane- fukukitaru（Full Armor）"],
"ばっちり開運体験！":["Matikane- fukukitaru（Full Armor）"],
"天翔る足取り":["Mr. C.B."],
"弾む大地":["Mr. C.B."],
"怒涛のスピード":["Meisho Doto"],
"諦めない、ですぅ～！":["Meisho Doto"],
"ライバルがいるから！":["Meisho Doto（Halloween）"],
"魂の導き手":["Meisho Doto（Halloween）"],
"クールな視線":["Mejiro Dober"],
"淀の女王":["Mejiro Dober"],
"もっと冒険してみたい！":["Mejiro Dober（Camping）"],
"起死回生の一歩":["Mejiro Dober（Camping）"],
"魅惑のシニカルガール":["Nice Nature"],
"目指せ！主人公！":["Nice Nature"],
"頑張るしかないよね":["Nice Nature（Cheerleader）"],
"ノンストップエール":["Nice Nature（Cheerleader）"],
"電撃の撫で切り":["King Halo"],
"王の大局観":["King Halo"],
"竜の雲を得る如し":["King Halo（Cheerleader）"],
"春風吹きて、桜舞う":["King Halo（Cheerleader）"],
"ゴーイングマイウェイ":["Matikane- tannhauser"],
"えい！えい！むん！":["Matikane- tannhauser"],
"パないっしょ？":["Mejiro Palmer"],
"神逃げの心得":["Mejiro Palmer"],
"マジ爆上げっしょ！":["Daitaku Helios"],
"とりまやったれ～！":["Daitaku Helios"],
"出力1000万%！！":["Twin Turbo"],
"ターボについてこーい！":["Twin Turbo"],
"金剛不壊":["Satono Diamond"],
"右回りの輪舞曲":["Satono Diamond"],
"無我の境地":["Satono Diamond（New Year）"],
"明けぬ夜はない！":["Satono Diamond（New Year）"],
"祭りだワッショイ！":["Kitasan Black"],
"爆風一閃！":["Kitasan Black"],
"未来へ飛び立ちましょう！":["Kitasan Black（New Year）"],
"必勝の前口上！":["Kitasan Black（New Year）"],
"お花見当たり年！":["Sakura Chiyono O"],
"けふ九重に満開です":["Sakura Chiyono O"],
"永遠の輝き":["Mejiro Ardan"],
"刹那への覚悟":["Mejiro Ardan"],
"昂る焔":["Yaeno Muteki"],
"八重の向こう意気":["Yaeno Muteki"],
"不屈のお嬢様":["Mejiro Bright"],
"動かざること羊蹄山の若し":["Mejiro Bright"],
"ウインドシアー":["Yamanin Zephyr"],
"神渡し":["Yamanin Zephyr"],
"必勝のピッチアップ":["Aston Machan"],
"記憶に刻む足取り":["Aston Machan"],
"コパッと開運！":["Copano Rickey"],
"龍脈の波濤":["Copano Rickey"],
"苫小牧グルメで舌鼓！":["Hokko Tarumae"],
"観光大使の面目躍如！":["Hokko Tarumae"],
"闘魂注入":["Wonder Acute"],
"女神の砂浴び":["Wonder Acute"],
"華麗であれ":["Daiichi Ruby"],
"常に最たる輝きを":["Daiichi Ruby"],
"質実剛健":["Symboli Kris S"],
"革命をもたらす威容":["Symboli Kris S"],
"桜花爛漫一直線":["Sakura Chiyono O（Ballroom）"],
"負けたくない！":["Sakura Chiyono O（Ballroom）"],
"美しき燐光":["Mejiro Ardan（Ballroom）"],
"淡く儚い残照":["Mejiro Ardan（Ballroom）"],
"桜前線進行中！":["Sakura Laurel"],
"一花咲かせましょう！":["Sakura Laurel"],
"銀河のその先へ、あなたと":["Neo Universe"],
"星の海を駆けて":["Neo Universe"],
"猪突猛進！バクシンロード！":["Sakura Bakushin O（Sports Festival）"],
"驀進！爆進！バクシーン！":["Sakura Bakushin O（Sports Festival）"],
"ポジティブスマイル":["Matikane- tannhauser（Sports Festival）"],
"大どんでんがえし":["Matikane- tannhauser（Sports Festival）"],
"焦らず、気負わず":["Hishi Miracle"],
"ちょっといいこと、集めて":["Hishi Miracle"],
"嵐を呼ぶ破壊神":["Tanino Gimlet"],
"酔い痴れよ、世界":["Tanino Gimlet"],
"熱烈エンゲージ！":["Hishi Amazon（Wedding）"],
"闘魂入刀！":["Hishi Amazon（Wedding）"],
"祝福のフラワーガール":["Nishino Flower（Wedding）"],
"ヴェール揺らす春疾風":["Nishino Flower（Wedding）"],
"ワクワク☆マーベラスゾーン":["Marvelous Sunday"],
"進め！世界マーベラス計画☆":["Marvelous Sunday"],
"ワンチャンまくったる！":["Tosen Jordan（Summer Trip）"],
"あたししか勝たん！":["Tosen Jordan（Summer Trip）"],
"熱血進化ライディング！":["Bamboo Memory（Summer Trip）"],
"必殺！爆速スプリント！":["Bamboo Memory（Summer Trip）"],
"してやったり！":["Katsuragi Ace"],
"逃げっ切りの1人旅":["Katsuragi Ace"],
"揺るがぬアスター":["Sirius Symboli"],
"一等星のアラベスク":["Sirius Symboli"],
"瑠璃色エスケイプ":["Silence Suzuka（Summer）"],
"蒼天を駆けるラーファガ":["Silence Suzuka（Summer）"],
"ラプラスの悪魔":["Agnes Tachyon（Summer）"],
"眩耀のルクシオン":["Agnes Tachyon（Summer）"],
"ターフの主人公":["Narita Top Road"],
"正道":["Narita Top Road"],
"押し寄せるジュテーム":["Gold Ship（Project L'Arc）"],
"荒磯好みの黄金船":["Gold Ship（Project L'Arc）"],
"蒼色革命":["Satono Diamond（Project L'Arc）"],
"ダンス・デ・レぺ":["Satono Diamond（Project L'Arc）"],
"K.Speed":["K.S.Miracle"],
"命の火花":["K.S.Miracle"],
"大物狙いの心得":["Seiun Sky"],
"Gluttony's Grip":["Air Shakur（Halloween）"],
"刑苦":["Air Shakur（Halloween）"],
"仕込みは完璧":["Eishin Flash（Valentine）"],
"サルビア☆スプレンデンス":["Sweep Tosho"],
"物語を紡ぐ者":["Zenno Rob Roy"],
"Burn Down":["Symboli Kris S（Halloween）"],
"Service: Transit":["Symboli Kris S（Halloween）"],
"純愛":["Mejiro Ramonu"],
"高嶺の艶笑":["Mejiro Ramonu"],
"天賦の身ごなし":["Tokai Teio（Festival）"],
"盤楽遊嬉":["Tokai Teio（Festival）"],
"飢えた怪物":["Oguri Cap"],
"粋でいなせな達人技":["Inari One"],
"トップ・オブ・ザ・姫！":["Kawakami Princess（Festival）"],
"爆走猛姫☆急転直下！！":["Kawakami Princess（Festival）"],
"目を逸らしちゃダメだよ☆":["Smart Falcon"],
"隠せぬ輝き":["Satono Diamond"],
"Breakaway Star":["Tap Dance City"],
"Smooth Sailing!":["Tap Dance City"],
"高まってきたぜぇ！！":["Gold Ship（Summer）"],
"コーナーに舞い降りし歌劇王":["TM Opera O（New Year）"],
"ちゃちゃっと始めんで！":["Tamamo Cross"],
"心に灯す闘志":["Meisho Doto（Halloween）"],
"北風一蹴":["Mejiro Palmer（Christmas）"],
"メリ☆クリ↑パーリー":["Mejiro Palmer（Christmas）"],
"聖夜の天路":["Mejiro Bright（Christmas）"],
"雪華の追い上げ":["Mejiro Bright（Christmas）"],
"アンビシャスカード":["Satono Crown"],
"ミリオンカード":["Satono Crown"],
"偉大なる踏破":["Cheval Grand"],
"全力投球":["Cheval Grand"],
"タイマンにかける執念":["Hishi Amazon"],
"狙うは最前ドセンへの道！":["Agnes Digital"],
"泥んこ魔王様":["Shinko Windy"],
"あっぱれ！臥竜勇往":["Kitasan Black（Anime Collab）"],
"万里飛び越えソイヤッ！":["Kitasan Black（Anime Collab）"],
"勝利に焦がれる激情":["Yaeno Muteki"],
"いい味、出てるでしょ？":["Nice Nature（New Year）"],
"大掃除上手":["Nice Nature（New Year）"],
"天来のリトルシスター":["Vivlos"],
"ハイソ・メンタリティ！":["Vivlos"],
"見惚れるコーナリング":["Fuji Kiseki（Ballroom）"],
"迫りくる宵闇":["Manhattan Cafe（Valentine）"],
"玄界領域":["Manhattan Cafe（Valentine）"],
"もうひとけっぱり！":["Yukino Bijin（Valentine）"],
"曲線に舞う深雪":["Yukino Bijin（Valentine）"],
"心奪われる閃光":["Curren Chan（Wedding）"],
"一輪の勇気":["Nishino Flower"],
"天つ風":["Yamanin Zephyr"],
"急行！ヒーロー参上！":["Biko Pegasus"],
"必殺・雷電キーック！":["Biko Pegasus"],
"キラメキの勝負":["UAFシナリオ"],
"燃えてきたッ！！":["UAFシナリオ"],
"ベストを尽くして！":["UAFシナリオ"],
"無二の情熱":["UAFシナリオ"],
"破竹の筋肉":["UAFシナリオ"],
"ステイチューン！":["UAFシナリオ"],
"繋がる高揚感":["UAFシナリオ"],
"徹底管理プラン":["Ikuno Dictus"],
"鉄火花":["Ikuno Dictus"],
"磨穿鉄硯":["Duramente"],
"赫焉":["Duramente"],
"情報強者":["Transcend"],
"『未知』を求めて":["Transcend"],
"未来を拓け！":["Rhein Kraft"],
"ぜーったい負けられない！":["Rhein Kraft"],
"コンドル跳躍術":["El Condor Pasa（Fantasy）"],
"理想へ向かう覚悟":["Fine Motion（Wedding）"],
"決意の根性娘":["Yukino Bijin"],
"自信持って踏み出して":["Mejiro Dober（Camping）"],
"トレンド先取り☆":["Daitaku Helios（Ballroom）"],
"マイル神、爆☆誕":["Daitaku Helios（Ballroom）"],
"霹靂閃電":["Daiichi Ruby（Ballroom）"],
"灰と化すまで":["Daiichi Ruby（Ballroom）"],
"全・力・ワク・ワク！！":["Winning Ticket（U.A.F.）"],
"Dreamer's Path":["Winning Ticket（U.A.F.）"],
"カエスーラ":["Sounds of Earth"],
"トライアンフ":["Sounds of Earth"],
"サプライズ大成功～☆":["Seiun Sky（Ballroom）"],
"流水流走":["Super Creek（Warfare）"],
"神仙蝶変の術":["Super Creek（Warfare）"],
"テンアゲスタイル":["Mejiro Palmer"],
"将の疾刃":["Yaeno Muteki（Warfare）"],
"無双の追撃":["Yaeno Muteki（Warfare）"],
"できる範囲でがんばろ～！":["Hishi Miracle"],
"光速を超える粒子":["Agnes Tachyon（Alt Version）"],
"被験体観察":["Agnes Tachyon（Alt Version）"],
"ココロ、キラめくままに！":["North Flight"],
"Enjoy the Flight":["North Flight"],
"シルフィード・マギア":["Sweep Tosho（Wedding）"],
"緊急魔力ブースト":["Sweep Tosho（Wedding）"],
"遮るものはない":["King Halo（Wedding）"],
"不屈の証明":["King Halo（Wedding）"],
"やばしやばし！":["Matikane- tannhauser（Sports Festival）"],
"案ずるより走るが速し":["Sakura Chiyono O"],
"追想のトロイメライ":["Sirius Symboli"],
"猛襲の牙":["Jungle Pocket"],
"闘叫の鬼":["Jungle Pocket"],
"天上天下唯我爆走":["Jungle Pocket"],
"敬愛ッ！ウママニア":["豊食祭シナリオ"],
"お待ちどおさま！":["豊食祭シナリオ"],
"ここらで味変！":["豊食祭シナリオ"],
"即席三ツ星コーナリング":["豊食祭シナリオ"],
"耕せ！開墾スプリント":["豊食祭シナリオ"],
"曲線のグランシェフ":["豊食祭シナリオ"],
"はっけよい！":["Hishi Akebono"],
"果てへの面舵":["Dream Journey"],
"夢見心地":["Dream Journey"],
"山頂でイタダキマス":["Rice Shower（Great Food Festival）"],
"淀の祝福":["Rice Shower（Great Food Festival）"],
"閃光一走！":["Calstone Light O"],
"突風一駆！":["Calstone Light O"],
"たぎってきたぁ～～っ！！":["Agnes Digital（Halloween）"],
"Ritter von Fuchu":["Eishin Flash（Summer Trip）"],
"閃光の奔流":["Eishin Flash（Summer Trip）"],
"最高峰のステージに！":["Smart Falcon（Grand Live）"],
"勝ちたいんだもん！":["Haru Urara（New Year）"],
"感謝のふるさとメドレー":["Hokko Tarumae（Summer Trip）"],
"突き進め北の海":["Hokko Tarumae（Summer Trip）"],
"いぶし銀の闘志":["Wonder Acute"],
"――お退きなさい":["Gentildonna"],
"Power Am I":["Gentildonna"],
"淑女の独擅場":["Gentildonna"],
"煌めく“キセキ”を":["Fuji Kiseki"],
"フィナーレの先頭へ":["Gold City"],
"勇躍閃々":["Zenno Rob Roy（Autumn）"],
"嵐纏いし英雄は往く":["Zenno Rob Roy（Autumn）"],
"龍虎相搏":["Bamboo Memory"],
"ルミナス・スペクトラム":["Neo Universe（Autumn）"],
"“METI”レゾナンス":["Neo Universe（Autumn）"],
"礎たれ":["Cesario"],
"麗しき転身":["Cesario"],
"忠心のヴェイヤンティフ":["Durandal"],
"オリファントの轟雷":["Durandal"],
"ほな、行くで！":["Tamamo Cross（Festival）"],
"お先に☆テールウィンド":["Mayano Top Gun（Halloween）"],
"コックピット・マジシャン":["Mayano Top Gun（Halloween）"],
"ミストラルに乗って":["Seeking the Pearl（Halloween）"],
"海の底からキラめいて…☆":["Seeking the Pearl（Halloween）"],
"あたしサイコーじゃん！":["Tosen Jordan（Summer Trip）"],
"幽玄の灯火":["Mejiro Ardan（Ballroom）"],
"俊傑の悠":["Bubble Gum Fellow"],
"嚆矢の花道":["Bubble Gum Fellow"],
"モンスターマシン":["メカウマ娘シナリオ"],
"リカバリーシーケンス":["メカウマ娘シナリオ"],
"システムオールグリーン":["メカウマ娘シナリオ"],
"リミッター解除":["メカウマ娘シナリオ"],
"先頭維持アルゴリズム":["メカウマ娘シナリオ"],
"弧線のトップスカラー":["メカウマ娘シナリオ"],
"滄海を越えしフーガ":["Silence Suzuka（Summer）"],
"シミュレートグラス・オン":["Biwa Hayahide（Mecha）"],
"ネオンの尾を引いて":["Biwa Hayahide（Mecha）"],
"ギュンギュンのマーベラス☆":["Marvelous Sunday"],
"栄光への羽ばたき":["Mejiro Dober"],
"ゼロレイテンシ":["Narita Taishin（Mecha）"],
"不撓のLimit Breaker":["Narita Taishin（Mecha）"],
"母の面影を追って":["Air Messiah"],
"堅実なる秘策":["Air Messiah"],
"朝腹、朝腹、かやすしや♪":["Tokai Teio（Festival）"],
"アル・ワーキを追いかけて":["Admire Vega（Christmas）"],
"氷星融解":["Admire Vega（Christmas）"],
"ノイズキャンセリング":["Air Shakur（Halloween）"],
"ひたむきサンタクロース":["Narita Top Road（Christmas）"],
"暗い夜道もお任せを！":["Narita Top Road（Christmas）"],
"グラン・ジュッテ":["Win Variation"],
"邁進アン・レール":["Win Variation"],
"射貫く蒼":["Grass Wonder（New Year）"],
"勝機到来":["Grass Wonder（New Year）"],
"甘さ控えめエスケープ":["Mihono Bourbon（Valentine）"],
"奪目の宙乗り":["Mr. C.B.（New Year）"],
"さァさ、お立ち合い！":["Mr. C.B.（New Year）"],
"伏竜は目覚めて":["Katsuragi Ace（New Year）"],
"暁光背負いて":["Katsuragi Ace（New Year）"],
"天女の羽衣":["Maruzensky（New Year）"],
"神薙ダンス":["Maruzensky（New Year）"],
"潮風の導き":["Furioso"],
"勇船直往":["Furioso"],
"一流の在り方":["King Halo（Wedding）"],
"塵旋風となりて":["Yamanin Zephyr（Valentine）"],
"シルフ・スピリット":["Yamanin Zephyr（Valentine）"],
"辻映りの妙技":["Aston Machan（Valentine）"],
"覚えていてくださいね？":["Aston Machan（Valentine）"],
"千辛万苦切り裂く刃":["Tsurumaru Tsuyoshi"],
"迸る月流星":["Tsurumaru Tsuyoshi"],
"伝説降臨":["Legendsシナリオ"],
"疾風より先へ":["Legendsシナリオ"],
"革命の岐路":["Legendsシナリオ"],
"夢の先駆者":["Legendsシナリオ"],
"幾星霜が導く一手":["Legendsシナリオ"],
"雲上飛翔":["Legendsシナリオ"],
"下弦の雪月花":["Yukino Bijin（Valentine）"],
"末永く、寄り添う花":["Nishino Flower（Wedding）"],
"我が意、即ち天の理なり":["Orfevre"],
"王威絢爛":["Orfevre"],
"――畏れよ、然して拝跪せよ":["Orfevre"],
"推してまいる！！":["Gran Alegria"],
"万哩へ響け大歓声":["Gran Alegria"],
"侵掠如火":["No Reason"],
"天下分け目":["No Reason"],
"韋駄天ノ襲脚":["Inari One（Festival）"],
"アレスの進撃":["Tanino Gimlet（Ballroom）"],
"アルテミスの矢":["Tanino Gimlet（Ballroom）"],
"True Wire-to-Wire!":["Tap Dance City（Ballroom）"],
"大航海、飄々と":["Tap Dance City（Ballroom）"],
"悪路のほうが好みでね":["Sirius Symboli（The Twinkle Legends）"],
"Beat the Stars":["Sirius Symboli（The Twinkle Legends）"],
"あんぱんと牛乳":["Fenomeno"],
"猛き獣は太陽に吼える":["Fenomeno"],
"立ち位置ゼロ番！":["Smart Falcon（Parade）"],
"爆レスあげちゃう☆":["Smart Falcon（Parade）"],
"黄龍、天へと昇る":["Copano Rickey（Parade）"],
"走る縁起物":["Copano Rickey（Parade）"],
"ひた走れ！苫小牧の星":["Hokko Tarumae"],
"不撓不屈の女王":["Verxina"],
"『お姉ちゃん、だもの』":["Verxina"],
"ストリーミング♡ラッシュ":["Loves Only You"],
"応援コメントよろしく！":["Loves Only You"],
"盛り上げ上手":["Nice Nature（New Year）"],
"Limitless Love":["Mejiro Ramonu（Wedding）"],
"祝宴の征服者":["Mejiro Ramonu（Wedding）"],
"栄華の歩み、誰ぞ遮る":["Cesario（Wedding）"],
"白妙の約定":["Cesario（Wedding）"],
"永永無窮":["Chrono Genesis"],
"創世の一頁":["Chrono Genesis"],
"開拓者の軌跡":["無人島シナリオ"],
"未知へのトライアル":["無人島シナリオ"],
"不屈のサバイバル魂":["無人島シナリオ"],
"大地を揺るがす疾走":["無人島シナリオ"],
"ワイルドアットハート":["無人島シナリオ"],
"大自然の鼓動":["無人島シナリオ"],
"誓いの一振り":["Hishi Amazon（Wedding）"],
"踏み出す勇気をご覧あれ":["Mejiro Ryan（Valentine）"],
"Wild Runway":["Gold City（Deserted Island）"],
"黄金の炎陽":["Gold City（Deserted Island）"],
"一番眺めのいい場所へ！":["Ines Fujin（Deserted Island）"],
"青空の下で待ってるよ！":["Ines Fujin（Deserted Island）"],
"希望は巡る、何度でも":["Rhein Kraft（Alt Version）"],
"ティアラ・ダイブ！":["Rhein Kraft（Alt Version）"],
"ラブミー☆パレード":["Fusaichi Pandora"],
"ぜーったい譲って♡":["Fusaichi Pandora"],
"緋色の光となって":["Daiwa Scarlet（Christmas）"],
"煌めきのイリュージョン":["Satono Crown（Summer）"],
"波上のラストトリック":["Satono Crown（Summer）"],
"マリンブルー・ライナー":["Cheval Grand（Summer）"],
"いつもの僕じゃないから！":["Cheval Grand（Summer）"],
"エスプロズィオーネ":["Sounds of Earth"],
"デザートジュエルに魅せられ":["Vivlos（Summer）"],
"いざ征かん！マリンロード":["Vivlos（Summer）"],
"赫き胎動":["Still in Love"],
"誰にも告げぬ誓い":["Still in Love"],
"呼び覚まされし願い":["Still in Love"],
"ディライトフルメモリー":["Fine Motion"],
"最っっっ高のプリンセス":["Kawakami Princess（Festival）"],
"ノクス・ルミナ":["Sweep Tosho（Wedding）"],
"『見ていて、くださいね』":["K.S.Miracle（Alt Version）"],
"彗星色の羽搏き":["K.S.Miracle（Alt Version）"],
"お邪魔しま～す♪":["Hishi Miracle（Alt Version）"],
"まさかここから大逆転！？":["Hishi Miracle（Alt Version）"],
"ベッコベコに凹ます！":["Espoir City"],
"相手が誰でも関係ねーし！":["Espoir City"],
"無極":["Believe"],
"徹骨徹髄":["Believe"],
"手招きシュガーランタン":["Hishi Akebono（Halloween）"],
"満たせ☆ぱんぷきんパワー！":["Hishi Akebono（Halloween）"],
"煌めき☆ドーリィステージ":["Marvelous Sunday（Halloween）"],
"いざ、ショーベラスタイム♪":["Marvelous Sunday（Halloween）"],
"我が一族の玉条を胸に":["Daiichi Ruby"],
"乗っとけ☆ぶち上げペース":["Tosen Jordan（Halloween）"],
"ここ、カマしどきっしょ！":["Tosen Jordan（Halloween）"],
"わたしだって、勝ちたい！！":["Dantsu Flame"],
"Ignite this Stage":["Dantsu Flame"],
"走り湯ダッシュ":["温泉シナリオ"],
"一番風呂いただきます！":["温泉シナリオ"],
"噴泉スピリット":["温泉シナリオ"],
"湯に入りて湯に入らざれ":["温泉シナリオ"],
"秘湯より湧くチカラ":["温泉シナリオ"],
"レッドゾーンを突き抜けて":["Maruzensky"],
"勝ち筋ドミネーション":["Transcend（Onsen）"],
"ここ、逃す手はないってね☆":["Transcend（Onsen）"],
"大地轟く大噴湯":["Wonder Acute（Onsen）"],
"風まかせ、お湯まかせ":["Wonder Acute（Onsen）"],
"ふたりの約束、とどく時":["Buena Vista"],
"誠心たる光燿":["Buena Vista"],
"未来へ続く放物線":["Air Groove（Wedding）"],
"一点張りでいこう":["Nakayama Festa（Christmas）"],
"勝負師の才略":["Nakayama Festa（Christmas）"],
"流れ星の軌跡":["K.S.Miracle"],
"雪暗れに微笑む":["Dream Journey（Christmas）"],
"さて、収めに参りましょう":["Dream Journey（Christmas）"],
"尽きぬ炎":["Oguri Cap（Anime Collab）"],
"天地を揺らせ君の名で":["Oguri Cap（Anime Collab）"],
"灰の怪物":["Oguri Cap（Anime Collab）"],
"見果てぬ旅路":["Stay Gold"],
"針が交わる時":["Stay Gold"],
"旅の心得":["Stay Gold"],
"陰りなき王道":["Symboli Rudolf"],
"怒涛のラッキー大猛進！":["Matikane- fukukitaru（Full Armor）"],
"梅仰ぎ、漕ぐ計路":["Ikuno Dictus（New Year）"],
"春道踏破":["Ikuno Dictus（New Year）"],
"初空高く、花宴":["Sakura Laurel（New Year）"],
"春めき、Lumière":["Sakura Laurel（New Year）"],
"風上に立て":["Bubble Gum Fellow（New Year）"],
"ハジける風雲児":["Bubble Gum Fellow（New Year）"],
"ブラッシュアップ！":["Kiseki"],
"緊急重版":["Kiseki"],
"渚の激マブウマ娘":["Maruzensky（Summer）"],
"飛び出せSheepy!":["Taiki Shuttle（Valentine）"],
"Sheep Stampede!":["Taiki Shuttle（Valentine）"],
"ムジカ・シンティッランテ":["Sounds of Earth（Valentine）"],
"ドーノ・ディ・フローラ！":["Sounds of Earth（Valentine）"],
"やってみせるんだ！！":["Rhein Kraft"],
"巧みなるファントム":["Royce and Royce"],
"認知度、急上昇！":["Royce and Royce"],
"スターダムを目指して！":["Dreamsシナリオ"],
"新しい夢への旅路":["Dreamsシナリオ"],
"Turn the tables!":["Dreamsシナリオ"],
"世界を魅せる輝き":["Dreamsシナリオ"],
"激アツ☆ロードマップ":["Dreamsシナリオ"],
"踊る脚色":["Mr. C.B."],
"熱踊の花道":["Kitasan Black"],
"The Next Phase":["Almond Eye"],
"確信された勝利":["Almond Eye"],
"革新された未来":["Almond Eye"],
"絶対は、ボクだ":["Tokai Teio（Anime Collab）"],
"最強の名を懸けて":["Mejiro McQueen（Anime Collab）"],
"シューティングスター":["Special Week"],
"先頭の景色は譲らない…！":["Silence Suzuka"],
"究極テイオーステップ":["Tokai Teio"],
"紅焔ギア/LP1211-M":["Maruzensky"],
"勝利の鼓動":["Oguri Cap"],
"ヴィクトリーショット！":["Taiki Shuttle"],
"貴顕の使命を果たすべく":["Mejiro McQueen"],
"ヴィットーリアに捧ぐ舞踏":["TM Opera O"],
"汝、皇帝の神威を見よ":["Symboli Rudolf"],
"∴win Q.E.D.":["Biwa Hayahide"],
"G00 1st.F∞;":["Mihono Bourbon"],
"ブルーローズチェイサー":["Rice Shower"],
"#LookatCurren":["Curren Chan"],
"Nemesis":["Narita Taishin"],
"キラキラ☆STARDOM":["Smart Falcon"],
"Shadow Break":["Narita Brian"],
"薫風、永遠なる瞬間を":["Air Groove（Wedding）"],
"フラワリー☆マニューバ":["Mayano Top Gun（Wedding）"],
"アングリング×スキーミング":["Seiun Sky"],
"タイマン！デッドヒート！":["Hishi Amazon"],
"ゲインヒール・スペリアー":["Grass Wonder（Fantasy）"],
"コンドル猛撃波":["El Condor Pasa（Fantasy）"],
"煌星のヴォードヴィル":["Fuji Kiseki"],
"KEEP IT REAL.":["Gold City"],
"わやかわ♪マリンダイヴ":["Special Week（Summer）"],
"グッときて♪Chu":["Maruzensky（Summer）"],
"I Never Goof Up!":["Meisho Doto"],
"Schwarzes Schwert":["Eishin Flash"],
"禾スナハチ登ル":["Matikane- fukukitaru（Full Armor）"],
"I'M☆FULL☆SPEED!!":["Hishi Akebono"],
"尊み☆ﾗｽﾄｽﾊﾟ—(ﾟ∀ﾟ)—ﾄ!":["Agnes Digital"],
"Drain for rose":["Rice Shower（Halloween）"],
"ぐるぐるマミートリック♡":["Super Creek（Halloween）"],
"姫たるもの、勝利をこの手に":["Kawakami Princess"],
"アナタヲ・オイカケテ":["Manhattan Cafe"],
"翳り退く、さざめきの矢":["Symboli Rudolf（Festival）"],
"GET DOWN":["Gold City（Festival）"],
"YEAH☆VIVID TIME!":["Tosen Jordan"],
"彼方、その先へ…":["Mejiro Dober"],
"聖夜のミラクルラン！":["Oguri Cap（Christmas）"],
"Presents from X":["Biwa Hayahide（Christmas）"],
"Fairy tale":["Fine Motion"],
"白い稲妻、見せたるで！":["Tamamo Cross"],
"恵福バルカローレ":["TM Opera O（New Year）"],
"113転び114起き":["Haru Urara（New Year）"],
"憧れは桜を越える！":["Sakura Chiyono O"],
"一期の夢、刹那の飛翔":["Mejiro Ardan"],
"オペレーション・Cacao":["Mihono Bourbon（Valentine）"],
"Guten Appetit♪":["Eishin Flash（Valentine）"],
"ディオスクロイの流星":["Admire Vega"],
"勝ち鬨ワッショイ！":["Kitasan Black"],
"晦冥を照らせ永遠の耀き":["Satono Diamond"],
"麗しき花信風":["Mejiro Bright"],
"Ravissant":["Fuji Kiseki（Ballroom）"],
"Do Ya Breakin!":["Seiun Sky（Ballroom）"],
"つぼみ、ほころぶ時":["Nishino Flower"],
"烈火繚乱、無敵之舞":["Yaeno Muteki"],
"Go☆Go☆for it!":["Nice Nature（Cheerleader）"],
"轟！トレセン応援団！！":["King Halo（Cheerleader）"],
"チャージ完了！全速前進！":["Ines Fujin"],
"ぶっちぎりロード":["Mejiro Palmer"],
"Best day ever":["Fine Motion（Wedding）"],
"One True Color":["Curren Chan（Wedding）"],
"快走かな、快走かな！":["Inari One"],
"いただき☆ストレリチア！":["Sweep Tosho"],
"Joyful Voyage!":["Taiki Shuttle（Camping）"],
"ときめきが呼ぶほうへ":["Mejiro Dober（Camping）"],
"trigger:BEAT":["Air Shakur"],
"威風堂々、夢錦！":["Special Week（Commander）"],
"日本総大将":["メインストーリー第一部"],
"不撓不屈":["メインストーリー第一部"],
"Adventure of 564":["Gold Ship（Summer）"],
"きらめくは海、まばゆきは君":["Mejiro McQueen（Summer）"],
"熱血！！風紀アタック":["Bamboo Memory"],
"理運開かりて翔る":["Copano Rickey"],
"α-star*":["Smart Falcon（Grand Live）"],
"夢の先へ、届け！":["Winning Ticket（Steampunk）"],
"Hephaistos":["Narita Taishin（Steampunk）"],
"ゆきあかり、おいかけて":["Yukino Bijin"],
"『I'm possible』":["Seeking the Pearl"],
"萌到讓我活過來了！":["Agnes Digital（Halloween）"],
"Spooky-Scary-Happy":["Meisho Doto（Halloween）"],
"Silent letter":["Aston Machan"],
"風光る":["Yamanin Zephyr"],
"火神鳴":["Tamamo Cross（Festival）"],
"灯穂":["Inari One（Festival）"],
"剣ヶ峰より、狂気に嗤え":["Nakayama Festa"],
"Never Say Never":["Wonder Acute"],
"Into High Gear!":["Vodka（Christmas）"],
"Queen's Lumination":["Daiwa Scarlet（Christmas）"],
"掲げよ、己が魂の剣を！":["Zenno Rob Roy"],
"灰色の臨界点":["Narita Brian（Blaze）"],
"玄雲散らす、黄金甲矢":["Satono Diamond（New Year）"],
"あっぱれ大盤振る舞い！":["Kitasan Black（New Year）"],
"かがやけ☆とまこまい":["Hokko Tarumae"],
"アゲてアゲてぷちょへんざ！":["Daitaku Helios"],
"あなたに捧げるフリーポア":["Mejiro Ryan（Valentine）"],
"フレッシュ☆パーラー":["Ines Fujin（Valentine）"],
"Ding Dong Boo":["Shinko Windy"],
"叙情、旅路の果てに":["Mr. C.B."],
"至上であれ":["Daiichi Ruby"],
"Mission: Triumph":["Symboli Kris S"],
"咲け咲け！私！":["Sakura Chiyono O（Ballroom）"],
"Danser le présent":["Mejiro Ardan（Ballroom）"],
"花開き、世界":["Sakura Laurel"],
"アド・アストラ":["Neo Universe"],
"CHERRY☆スクランブル":["Sakura Bakushin O（Sports Festival）"],
"ごろりん！？パワードライブ":["Matikane- tannhauser（Sports Festival）"],
"Bang☆ミラクるわせ！":["Hishi Miracle"],
"霹靂のアウフヘーベン":["Tanino Gimlet"],
"大盛り！ファーストバイト！":["Hishi Amazon（Wedding）"],
"Flowering Dreams":["Nishino Flower（Wedding）"],
"万彩☆マーベラス★世界":["Marvelous Sunday"],
"GALmem.ふぉーえば♪":["Tosen Jordan（Summer Trip）"],
"奥義・常夏バーニング！！":["Bamboo Memory（Summer Trip）"],
"暁の御旗『葛城栄主』！":["Katsuragi Ace"],
"セイリオス":["Sirius Symboli"],
"水平線のその先へ":["Silence Suzuka（Summer）"],
"夏空ハレーション":["Agnes Tachyon（Summer）"],
"Road to Glory":["Narita Top Road"],
"Vive la GOLD":["Gold Ship（Project L'Arc）"],
"ポンテ・デ・ディアマン":["Satono Diamond（Project L'Arc）"],
"幸せの青い光":["K.S.Miracle"],
"...found you.":["Air Shakur（Halloween）"],
"Immortal Work":["Symboli Kris S（Halloween）"],
"愛と熔けよただ熔けよ":["Mejiro Ramonu"],
"快なる剛力":["Kawakami Princess（Festival）"],
"歌舞歓楽や、ああをかし":["Tokai Teio（Festival）"],
"Billions of stars":["Tap Dance City"],
"jingle all the way":["Mejiro Palmer（Christmas）"],
"Illuminate you":["Mejiro Bright（Christmas）"],
"Reversal Illusion":["Satono Crown"],
"Celeste Oath":["Cheval Grand"],
"ミンナノアタシへ！":["Kitasan Black（Anime Collab）"],
"マスターズドライブ":["マスターズチャレンジ"],
"もちっと・ハレハレ":["Nice Nature（New Year）"],
"デラックス☆ファウンテン":["Vivlos"],
"心からのおもてにゃし":["Manhattan Cafe（Valentine）"],
"いっぱいおあげんしぇ！":["Yukino Bijin（Valentine）"],
"羅刹、赤翼にて天上へ至らん":["Duramente"],
"Info: Acquired":["Transcend"],
"繋ぐ・繋がる×夢・未来":["Rhein Kraft"],
"ノッてけ、マッシュアップ！":["Daitaku Helios（Ballroom）"],
"蒼炎":["Daiichi Ruby（Ballroom）"],
"GO! Full-send":["Winning Ticket（U.A.F.）"],
"ヴィヴァーチェ・ヴォラーレ":["Sounds of Earth"],
"剛勇果断、烈火之刀":["Yaeno Muteki（Warfare）"],
"忍法・ほほえみ心結の印":["Super Creek（Warfare）"],
"超光速微粒子の可能性":["Agnes Tachyon（Alt Version）"],
"Shining Runway":["North Flight"],
"とっておきmaterialize":["Sweep Tosho（Wedding）"],
"理想へのwinding road":["King Halo（Wedding）"],
"Faith in the Feral":["Jungle Pocket"],
"『それでは、よき旅を』":["Dream Journey"],
"あおぞらクッキング♪":["Rice Shower（Great Food Festival）"],
"無二無三なる一条の路":["Calstone Light O"],
"とびだせ☆ポッピングシェル":["Hokko Tarumae（Summer Trip）"],
"潮風のGeschenk":["Eishin Flash（Summer Trip）"],
"烈華の洗礼":["Gentildonna"],
"未知との遭遇、即ち物語":["Zenno Rob Roy（Autumn）"],
"Encounter with U":["Neo Universe（Autumn）"],
"Guiding Sea":["Cesario"],
"Lame de vent":["Durandal"],
"Oh!bento-magic☆":["Seeking the Pearl（Halloween）"],
"HOP STEP♪LOCK ON!":["Mayano Top Gun（Halloween）"],
"ふくらむ夢、先駆の途":["Bubble Gum Fellow"],
"勝利ヘ至ル累積":["Biwa Hayahide（Mecha）"],
"Overdrive Speed":["Narita Taishin（Mecha）"],
"辿る血脈、芽吹く未来":["Air Messiah"],
"Crystal Mist":["Admire Vega（Christmas）"],
"Joy to the World":["Narita Top Road（Christmas）"],
"鋭気のアレグロ":["Win Variation"],
"演舞・撫子大薙刀":["Grass Wonder（New Year）"],
"爛然闊歩":["Mr. C.B.（New Year）"],
"決意一筆":["Katsuragi Ace（New Year）"],
"霊験灼然チョベリグ神託":["Maruzensky（New Year）"],
"『船橋最強！』":["Furioso"],
"Breezy Treat":["Yamanin Zephyr（Valentine）"],
"ふわもこアワー":["Aston Machan（Valentine）"],
"我が覇道、阻むものなし":["Orfevre"],
"¡Qué alegría!":["Gran Alegria"],
"知宵欺敵、百戦不殆":["No Reason"],
"深淵のテルプシコラー":["Tanino Gimlet（Ballroom）"],
"Romantic Horizon":["Tap Dance City（Ballroom）"],
"レジェンダリーアクセル":["マスターズチャレンジ"],
"駆るは光、狩るは星々":["Sirius Symboli（The Twinkle Legends）"],
"対象捕捉！正義遂行！":["Fenomeno"],
"五獣挙りて彩光奏づ":["Copano Rickey（Parade）"],
"Forward March!":["Smart Falcon（Parade）"],
"Queen's Rebirth":["Verxina"],
"Circulating Love♡":["Loves Only You"],
"解けぬ結い目":["Mejiro Ramonu（Wedding）"],
"時かけるせせらぎ":["Cesario（Wedding）"],
"Weaving History":["Chrono Genesis"],
"Silent Sunset Gold":["Gold City（Deserted Island）"],
"全力全開！サイクロン":["Ines Fujin（Deserted Island）"],
"ホップステップ・ゲッチュ♡":["Fusaichi Pandora"],
"ずっとずっと輝いて":["Rhein Kraft（Alt Version）"],
"夏雷カスケード！":["Satono Crown（Summer）"],
"Tidebreaker":["Cheval Grand（Summer）"],
"ジュ・テーム☆バカンス！":["Vivlos（Summer）"],
"スカーレットリリィの高揚":["Still in Love"],
"きせき・おもい・かなで":["K.S.Miracle（Alt Version）"],
"小さな奇跡、フォーユー♪":["Hishi Miracle（Alt Version）"],
"Punkish Bite":["Espoir City"],
"念い、信ずればこそ":["Believe"],
"シュガーパレード・始動！":["Hishi Akebono（Halloween）"],
"喝采☆ワンダードール！":["Marvelous Sunday（Halloween）"],
"ヤバ技☆ジャグルビート":["Tosen Jordan（Halloween）"],
"照らすのはわたしの焔":["Dantsu Flame"],
"地熱解放オーヴァードライブ":["Transcend（Onsen）"],
"湯守の和心":["Wonder Acute（Onsen）"],
"To Our Vista":["Buena Vista"],
"運否、聖夜の星に賭ける":["Nakayama Festa（Christmas）"],
"夢寐に見る銀世界":["Dream Journey（Christmas）"],
"灰の光跡：シンデレラグレイ":["Oguri Cap（Anime Collab）"],
"黄金を訪ねて":["Stay Gold"],
"千歳、廻りて":["Ikuno Dictus（New Year）"],
"春光・Bon appétit":["Sakura Laurel（New Year）"],
"暁霞を拓き、朝を掴む":["Bubble Gum Fellow（New Year）"],
"想像×創造＝∞":["Kiseki"],
"ケ・ピアチェーヴォレ！":["Sounds of Earth（Valentine）"],
"Have S'more Love!":["Taiki Shuttle（Valentine）"],
"Peerless Heroine":["Almond Eye"],
"不沈艦、抜錨ォッ！":["Gold Ship"],
"カッティング×DRIVE！":["Vodka"],
"ブリリアント・レッドエース":["Daiwa Scarlet"],
"精神一到何事か成らざらん":["Grass Wonder"],
"プランチャ☆ガナドール":["El Condor Pasa"],
"ブレイズ・オブ・プライド":["Air Groove"],
"ひらめき☆ランディング":["Mayano Top Gun"],
"レッツ・アナボリック！":["Mejiro Ryan"],
"U=ma2":["Agnes Tachyon"],
"勝利のチケットを、君にッ！":["Winning Ticket"],
"優等生×バクシン＝大勝利ッ":["Sakura Bakushin O"],
"ピュリティオブハート":["Super Creek"],
"ワクワククライマックス":["Haru Urara"],
"来ます来てます来させます！":["Matikane- fukukitaru"],
"きっとその先へ…！":["Nice Nature"],
"Pride of KING":["King Halo"],
"どんっ、パッ、むんっ":["Matikane- tannhauser"],
"エンジン全開！大噴射！":["Twin Turbo"],
"疾風爆走ペガサスダッシュ！":["Biko Pegasus"],
"百錬成鋼":["Ikuno Dictus"],
"燃え盛るは絶対の意志":["Tsurumaru Tsuyoshi"],
"絶対最強☆アピール宣言！":["Royce and Royce"],
"波乱注意砲！":["Gold Ship"],
"アクセルX":["Vodka"],
"レッドエース":["Daiwa Scarlet"],
"精神一到":["Grass Wonder"],
"熱血☆アミーゴ":["El Condor Pasa"],
"エンプレス・プライド":["Air Groove"],
"勝利のキッス☆":["Mayano Top Gun"],
"燃えろ筋肉！":["Mejiro Ryan"],
"introduction：My body":["Agnes Tachyon"],
"全力Vサインッ！":["Winning Ticket"],
"学級委員長+速さ＝バクシン":["Sakura Bakushin O"],
"クリアハート":["Super Creek"],
"ワクワクよーいドン":["Haru Urara"],
"来てください来てください！":["Matikane- fukukitaru"],
"アタシもたまには、ね？":["Nice Nature"],
"Call me KING":["King Halo"],
"レディー、どんっ！":["Matikane- tannhauser"],
"エンジン点火！":["Twin Turbo"],
"ペガサスフルパワー！":["Biko Pegasus"],
"打ち、鍛えて":["Ikuno Dictus"],
"心、強し！":["Tsurumaru Tsuyoshi"],
"アピール宣言！":["Royce and Royce"]};